# Generated by Django 3.2.5 on 2023-02-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='describing_keyword',
            field=models.CharField(default='Default', help_text='max-255', max_length=255, verbose_name='keyword describing product'),
            preserve_default=False,
        ),
    ]
