# Generated by Django 3.2.5 on 2023-02-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productinventory_describing_keyword'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productinventory',
            unique_together={('product', 'describing_keyword')},
        ),
    ]
