# Generated by Django 3.2.5 on 2023-02-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_productinventory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='describing_keyword',
            field=models.CharField(blank=True, help_text='max-255', max_length=255, null=True, verbose_name='keyword describing product'),
        ),
    ]
