# Generated by Django 4.1 on 2023-03-23 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_productinventory_describing_keyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinventory",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="brand",
                to="inventory.brand",
            ),
        ),
        migrations.AlterField(
            model_name="productinventory",
            name="retail_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                error_messages={
                    "name": {"max_length": "the price must be between 0 and 999.99."}
                },
                help_text="format: maximum price 999.99",
                max_digits=5,
                null=True,
                verbose_name="recommended retail price",
            ),
        ),
        migrations.AlterField(
            model_name="productinventory",
            name="sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                error_messages={
                    "name": {"max_length": "the price must be between 0 and 999.99."}
                },
                help_text="format: maximum price 999.99",
                max_digits=5,
                null=True,
                verbose_name="sale price",
            ),
        ),
        migrations.AlterField(
            model_name="productinventory",
            name="upc",
            field=models.CharField(
                blank=True,
                help_text="format: required, unique, max-12",
                max_length=12,
                null=True,
                unique=True,
                verbose_name="universal product code",
            ),
        ),
    ]
