# Generated by Django 4.1 on 2023-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_media_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinventory",
            name="weight",
            field=models.FloatField(
                blank=True, null=True, verbose_name="product weight"
            ),
        ),
    ]
