# Generated by Django 3.2.5 on 2023-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('web_id', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(default='defaults/placeholder.png', upload_to='uploads/captchas/')),
            ],
            options={
                'verbose_name': 'Captcha',
                'verbose_name_plural': 'Captchas',
                'db_table': 'captcha',
            },
        ),
    ]
