# Generated by Django 4.1 on 2023-03-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extenduser",
            name="balance",
            field=models.DecimalField(
                decimal_places=5, default=0, max_digits=10, verbose_name="balence"
            ),
        ),
    ]
