# Generated by Django 3.2.5 on 2023-02-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
