# Generated by Django 3.2.5 on 2023-02-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20230211_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinvoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
