# Generated by Django 4.1 on 2023-03-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_orderinvoice_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_key",
            field=models.CharField(default="a", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
