# Generated by Django 4.1 on 2023-03-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_order_order_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_key",
            new_name="code",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("new", "new"),
                    ("paid", "paid"),
                    ("shipped", "shipped"),
                    ("canceled", "canceled"),
                ],
                default="new",
                max_length=255,
            ),
        ),
    ]
