# Generated by Django 4.2 on 2023-05-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketobject",
            name="product_inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baskets",
                to="inventory.productinventory",
            ),
        ),
    ]
